/*
 * This file is generated by jOOQ.
 */
package store.pengu.server.db.pengustore.tables.pojos;


import java.io.Serializable;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CrowdProductImages implements Serializable {

    private static final long serialVersionUID = 1L;

    private final ULong  id;
    private final String barcode;
    private final String imageUrl;

    public CrowdProductImages(CrowdProductImages value) {
        this.id = value.id;
        this.barcode = value.barcode;
        this.imageUrl = value.imageUrl;
    }

    public CrowdProductImages(
        ULong  id,
        String barcode,
        String imageUrl
    ) {
        this.id = id;
        this.barcode = barcode;
        this.imageUrl = imageUrl;
    }

    /**
     * Getter for <code>crowd_product_images.id</code>.
     */
    public ULong getId() {
        return this.id;
    }

    /**
     * Getter for <code>crowd_product_images.barcode</code>.
     */
    public String getBarcode() {
        return this.barcode;
    }

    /**
     * Getter for <code>crowd_product_images.image_url</code>.
     */
    public String getImageUrl() {
        return this.imageUrl;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CrowdProductImages (");

        sb.append(id);
        sb.append(", ").append(barcode);
        sb.append(", ").append(imageUrl);

        sb.append(")");
        return sb.toString();
    }
}
