/*
 * This file is generated by jOOQ.
 */
package store.pengu.server.db.pengustore.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CrowdProductPrices implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String barcode;
    private final Double price;
    private final Double latitude;
    private final Double longitude;

    public CrowdProductPrices(CrowdProductPrices value) {
        this.barcode = value.barcode;
        this.price = value.price;
        this.latitude = value.latitude;
        this.longitude = value.longitude;
    }

    public CrowdProductPrices(
        String barcode,
        Double price,
        Double latitude,
        Double longitude
    ) {
        this.barcode = barcode;
        this.price = price;
        this.latitude = latitude;
        this.longitude = longitude;
    }

    /**
     * Getter for <code>crowd_product_prices.barcode</code>.
     */
    public String getBarcode() {
        return this.barcode;
    }

    /**
     * Getter for <code>crowd_product_prices.price</code>.
     */
    public Double getPrice() {
        return this.price;
    }

    /**
     * Getter for <code>crowd_product_prices.latitude</code>.
     */
    public Double getLatitude() {
        return this.latitude;
    }

    /**
     * Getter for <code>crowd_product_prices.longitude</code>.
     */
    public Double getLongitude() {
        return this.longitude;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CrowdProductPrices (");

        sb.append(barcode);
        sb.append(", ").append(price);
        sb.append(", ").append(latitude);
        sb.append(", ").append(longitude);

        sb.append(")");
        return sb.toString();
    }
}
