/*
 * This file is generated by jOOQ.
 */
package store.pengu.server.db.pengustore.tables.pojos;


import java.io.Serializable;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LocalProductPrices implements Serializable {

    private static final long serialVersionUID = 1L;

    private final ULong  productId;
    private final Double price;
    private final Double latitude;
    private final Double longitude;

    public LocalProductPrices(LocalProductPrices value) {
        this.productId = value.productId;
        this.price = value.price;
        this.latitude = value.latitude;
        this.longitude = value.longitude;
    }

    public LocalProductPrices(
        ULong  productId,
        Double price,
        Double latitude,
        Double longitude
    ) {
        this.productId = productId;
        this.price = price;
        this.latitude = latitude;
        this.longitude = longitude;
    }

    /**
     * Getter for <code>local_product_prices.product_id</code>.
     */
    public ULong getProductId() {
        return this.productId;
    }

    /**
     * Getter for <code>local_product_prices.price</code>.
     */
    public Double getPrice() {
        return this.price;
    }

    /**
     * Getter for <code>local_product_prices.latitude</code>.
     */
    public Double getLatitude() {
        return this.latitude;
    }

    /**
     * Getter for <code>local_product_prices.longitude</code>.
     */
    public Double getLongitude() {
        return this.longitude;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LocalProductPrices (");

        sb.append(productId);
        sb.append(", ").append(price);
        sb.append(", ").append(latitude);
        sb.append(", ").append(longitude);

        sb.append(")");
        return sb.toString();
    }
}
