/*
 * This file is generated by jOOQ.
 */
package store.pengu.server.db.pengustore.tables.pojos;


import java.io.Serializable;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PantryProducts implements Serializable {

    private static final long serialVersionUID = 1L;

    private final ULong   pantryId;
    private final ULong   productId;
    private final Integer haveQty;
    private final Integer wantQty;

    public PantryProducts(PantryProducts value) {
        this.pantryId = value.pantryId;
        this.productId = value.productId;
        this.haveQty = value.haveQty;
        this.wantQty = value.wantQty;
    }

    public PantryProducts(
        ULong   pantryId,
        ULong   productId,
        Integer haveQty,
        Integer wantQty
    ) {
        this.pantryId = pantryId;
        this.productId = productId;
        this.haveQty = haveQty;
        this.wantQty = wantQty;
    }

    /**
     * Getter for <code>pantry_products.pantry_id</code>.
     */
    public ULong getPantryId() {
        return this.pantryId;
    }

    /**
     * Getter for <code>pantry_products.product_id</code>.
     */
    public ULong getProductId() {
        return this.productId;
    }

    /**
     * Getter for <code>pantry_products.have_qty</code>.
     */
    public Integer getHaveQty() {
        return this.haveQty;
    }

    /**
     * Getter for <code>pantry_products.want_qty</code>.
     */
    public Integer getWantQty() {
        return this.wantQty;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PantryProducts (");

        sb.append(pantryId);
        sb.append(", ").append(productId);
        sb.append(", ").append(haveQty);
        sb.append(", ").append(wantQty);

        sb.append(")");
        return sb.toString();
    }
}
