/*
 * This file is generated by jOOQ.
 */
package store.pengu.server.db.pengustore.tables.pojos;


import java.io.Serializable;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Pantries implements Serializable {

    private static final long serialVersionUID = 1L;

    private final ULong  pantryId;
    private final String code;
    private final String name;

    public Pantries(Pantries value) {
        this.pantryId = value.pantryId;
        this.code = value.code;
        this.name = value.name;
    }

    public Pantries(
        ULong  pantryId,
        String code,
        String name
    ) {
        this.pantryId = pantryId;
        this.code = code;
        this.name = name;
    }

    /**
     * Getter for <code>pantries.pantry_id</code>.
     */
    public ULong getPantryId() {
        return this.pantryId;
    }

    /**
     * Getter for <code>pantries.code</code>.
     */
    public String getCode() {
        return this.code;
    }

    /**
     * Getter for <code>pantries.name</code>.
     */
    public String getName() {
        return this.name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Pantries (");

        sb.append(pantryId);
        sb.append(", ").append(code);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
