/*
 * This file is generated by jOOQ.
 */
package store.pengu.server.db.pengustore.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PantryXUser implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long pantryId;
    private final Long userId;

    public PantryXUser(PantryXUser value) {
        this.pantryId = value.pantryId;
        this.userId = value.userId;
    }

    public PantryXUser(
        Long pantryId,
        Long userId
    ) {
        this.pantryId = pantryId;
        this.userId = userId;
    }

    /**
     * Getter for <code>pantry_x_user.pantry_id</code>.
     */
    public Long getPantryId() {
        return this.pantryId;
    }

    /**
     * Getter for <code>pantry_x_user.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PantryXUser (");

        sb.append(pantryId);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
