/*
 * This file is generated by jOOQ.
 */
package store.pengu.server.db.pengustore.tables.pojos;


import java.io.Serializable;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Pantries implements Serializable {

    private static final long serialVersionUID = 1L;

    private final ULong  id;
    private final String code;
    private final String name;
    private final Double latitude;
    private final Double longitude;
    private final String color;

    public Pantries(Pantries value) {
        this.id = value.id;
        this.code = value.code;
        this.name = value.name;
        this.latitude = value.latitude;
        this.longitude = value.longitude;
        this.color = value.color;
    }

    public Pantries(
        ULong  id,
        String code,
        String name,
        Double latitude,
        Double longitude,
        String color
    ) {
        this.id = id;
        this.code = code;
        this.name = name;
        this.latitude = latitude;
        this.longitude = longitude;
        this.color = color;
    }

    /**
     * Getter for <code>pantries.id</code>.
     */
    public ULong getId() {
        return this.id;
    }

    /**
     * Getter for <code>pantries.code</code>.
     */
    public String getCode() {
        return this.code;
    }

    /**
     * Getter for <code>pantries.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>pantries.latitude</code>.
     */
    public Double getLatitude() {
        return this.latitude;
    }

    /**
     * Getter for <code>pantries.longitude</code>.
     */
    public Double getLongitude() {
        return this.longitude;
    }

    /**
     * Getter for <code>pantries.color</code>.
     */
    public String getColor() {
        return this.color;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Pantries (");

        sb.append(id);
        sb.append(", ").append(code);
        sb.append(", ").append(name);
        sb.append(", ").append(latitude);
        sb.append(", ").append(longitude);
        sb.append(", ").append(color);

        sb.append(")");
        return sb.toString();
    }
}
