/*
 * This file is generated by jOOQ.
 */
package store.pengu.server.db.pengustore.tables.pojos;


import java.io.Serializable;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PantriesUsers implements Serializable {

    private static final long serialVersionUID = 1L;

    private final ULong pantryId;
    private final ULong userId;

    public PantriesUsers(PantriesUsers value) {
        this.pantryId = value.pantryId;
        this.userId = value.userId;
    }

    public PantriesUsers(
        ULong pantryId,
        ULong userId
    ) {
        this.pantryId = pantryId;
        this.userId = userId;
    }

    /**
     * Getter for <code>pantries_users.pantry_id</code>.
     */
    public ULong getPantryId() {
        return this.pantryId;
    }

    /**
     * Getter for <code>pantries_users.user_id</code>.
     */
    public ULong getUserId() {
        return this.userId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PantriesUsers (");

        sb.append(pantryId);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
