/*
 * This file is generated by jOOQ.
 */
package store.pengu.server.db.pengustore.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductXPantry implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long    pantryId;
    private final Long    productId;
    private final Integer haveQty;
    private final Integer wantQty;

    public ProductXPantry(ProductXPantry value) {
        this.pantryId = value.pantryId;
        this.productId = value.productId;
        this.haveQty = value.haveQty;
        this.wantQty = value.wantQty;
    }

    public ProductXPantry(
        Long    pantryId,
        Long    productId,
        Integer haveQty,
        Integer wantQty
    ) {
        this.pantryId = pantryId;
        this.productId = productId;
        this.haveQty = haveQty;
        this.wantQty = wantQty;
    }

    /**
     * Getter for <code>product_x_pantry.pantry_id</code>.
     */
    public Long getPantryId() {
        return this.pantryId;
    }

    /**
     * Getter for <code>product_x_pantry.product_id</code>.
     */
    public Long getProductId() {
        return this.productId;
    }

    /**
     * Getter for <code>product_x_pantry.have_qty</code>.
     */
    public Integer getHaveQty() {
        return this.haveQty;
    }

    /**
     * Getter for <code>product_x_pantry.want_qty</code>.
     */
    public Integer getWantQty() {
        return this.wantQty;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProductXPantry (");

        sb.append(pantryId);
        sb.append(", ").append(productId);
        sb.append(", ").append(haveQty);
        sb.append(", ").append(wantQty);

        sb.append(")");
        return sb.toString();
    }
}
