/*
 * This file is generated by jOOQ.
 */
package store.pengu.server.db.pengustore.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductXImage implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long   productId;
    private final byte[] image;

    public ProductXImage(ProductXImage value) {
        this.productId = value.productId;
        this.image = value.image;
    }

    public ProductXImage(
        Long   productId,
        byte[] image
    ) {
        this.productId = productId;
        this.image = image;
    }

    /**
     * Getter for <code>product_x_image.product_id</code>.
     */
    public Long getProductId() {
        return this.productId;
    }

    /**
     * Getter for <code>product_x_image.image</code>.
     */
    public byte[] getImage() {
        return this.image;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProductXImage (");

        sb.append(productId);
        sb.append(", ").append("[binary...]");

        sb.append(")");
        return sb.toString();
    }
}
