/*
 * This file is generated by jOOQ.
 */
package store.pengu.server.db.pengustore.tables.pojos;


import java.io.Serializable;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductsUsers implements Serializable {

    private static final long serialVersionUID = 1L;

    private final ULong productId;
    private final ULong userId;

    public ProductsUsers(ProductsUsers value) {
        this.productId = value.productId;
        this.userId = value.userId;
    }

    public ProductsUsers(
        ULong productId,
        ULong userId
    ) {
        this.productId = productId;
        this.userId = userId;
    }

    /**
     * Getter for <code>products_users.product_id</code>.
     */
    public ULong getProductId() {
        return this.productId;
    }

    /**
     * Getter for <code>products_users.user_id</code>.
     */
    public ULong getUserId() {
        return this.userId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProductsUsers (");

        sb.append(productId);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
