/*
 * This file is generated by jOOQ.
 */
package store.pengu.server.db.pengustore.tables.pojos;


import java.io.Serializable;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Products implements Serializable {

    private static final long serialVersionUID = 1L;

    private final ULong   productId;
    private final String  barcode;
    private final Double  reviewScore;
    private final Integer reviewNumber;
    private final String  name;

    public Products(Products value) {
        this.productId = value.productId;
        this.barcode = value.barcode;
        this.reviewScore = value.reviewScore;
        this.reviewNumber = value.reviewNumber;
        this.name = value.name;
    }

    public Products(
        ULong   productId,
        String  barcode,
        Double  reviewScore,
        Integer reviewNumber,
        String  name
    ) {
        this.productId = productId;
        this.barcode = barcode;
        this.reviewScore = reviewScore;
        this.reviewNumber = reviewNumber;
        this.name = name;
    }

    /**
     * Getter for <code>products.product_id</code>.
     */
    public ULong getProductId() {
        return this.productId;
    }

    /**
     * Getter for <code>products.barcode</code>.
     */
    public String getBarcode() {
        return this.barcode;
    }

    /**
     * Getter for <code>products.review_score</code>.
     */
    public Double getReviewScore() {
        return this.reviewScore;
    }

    /**
     * Getter for <code>products.review_number</code>.
     */
    public Integer getReviewNumber() {
        return this.reviewNumber;
    }

    /**
     * Getter for <code>products.name</code>.
     */
    public String getName() {
        return this.name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Products (");

        sb.append(productId);
        sb.append(", ").append(barcode);
        sb.append(", ").append(reviewScore);
        sb.append(", ").append(reviewNumber);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
