/*
 * This file is generated by jOOQ.
 */
package store.pengu.server.db.pengustore.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShopXProduct implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long   shopId;
    private final Long   productId;
    private final Double price;

    public ShopXProduct(ShopXProduct value) {
        this.shopId = value.shopId;
        this.productId = value.productId;
        this.price = value.price;
    }

    public ShopXProduct(
        Long   shopId,
        Long   productId,
        Double price
    ) {
        this.shopId = shopId;
        this.productId = productId;
        this.price = price;
    }

    /**
     * Getter for <code>shop_x_product.shop_id</code>.
     */
    public Long getShopId() {
        return this.shopId;
    }

    /**
     * Getter for <code>shop_x_product.product_id</code>.
     */
    public Long getProductId() {
        return this.productId;
    }

    /**
     * Getter for <code>shop_x_product.price</code>.
     */
    public Double getPrice() {
        return this.price;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ShopXProduct (");

        sb.append(shopId);
        sb.append(", ").append(productId);
        sb.append(", ").append(price);

        sb.append(")");
        return sb.toString();
    }
}
