/*
 * This file is generated by jOOQ.
 */
package store.pengu.server.db.pengustore.tables.pojos;


import java.io.Serializable;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Shops implements Serializable {

    private static final long serialVersionUID = 1L;

    private final ULong  shopId;
    private final String name;
    private final Double locationX;
    private final Double locationY;

    public Shops(Shops value) {
        this.shopId = value.shopId;
        this.name = value.name;
        this.locationX = value.locationX;
        this.locationY = value.locationY;
    }

    public Shops(
        ULong  shopId,
        String name,
        Double locationX,
        Double locationY
    ) {
        this.shopId = shopId;
        this.name = name;
        this.locationX = locationX;
        this.locationY = locationY;
    }

    /**
     * Getter for <code>shops.shop_id</code>.
     */
    public ULong getShopId() {
        return this.shopId;
    }

    /**
     * Getter for <code>shops.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>shops.location_x</code>.
     */
    public Double getLocationX() {
        return this.locationX;
    }

    /**
     * Getter for <code>shops.location_y</code>.
     */
    public Double getLocationY() {
        return this.locationY;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Shops (");

        sb.append(shopId);
        sb.append(", ").append(name);
        sb.append(", ").append(locationX);
        sb.append(", ").append(locationY);

        sb.append(")");
        return sb.toString();
    }
}
