/*
 * This file is generated by jOOQ.
 */
package store.pengu.server.db.pengustore.tables.pojos;


import java.io.Serializable;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShoppingListUsers implements Serializable {

    private static final long serialVersionUID = 1L;

    private final ULong shoppingListId;
    private final ULong userId;

    public ShoppingListUsers(ShoppingListUsers value) {
        this.shoppingListId = value.shoppingListId;
        this.userId = value.userId;
    }

    public ShoppingListUsers(
        ULong shoppingListId,
        ULong userId
    ) {
        this.shoppingListId = shoppingListId;
        this.userId = userId;
    }

    /**
     * Getter for <code>shopping_list_users.shopping_list_id</code>.
     */
    public ULong getShoppingListId() {
        return this.shoppingListId;
    }

    /**
     * Getter for <code>shopping_list_users.user_id</code>.
     */
    public ULong getUserId() {
        return this.userId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ShoppingListUsers (");

        sb.append(shoppingListId);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
