/*
 * This file is generated by jOOQ.
 */
package store.pengu.server.db.pengustore.tables.pojos;


import java.io.Serializable;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Shops implements Serializable {

    private static final long serialVersionUID = 1L;

    private final ULong  shopId;
    private final String name;
    private final Double latitude;
    private final Double longitude;

    public Shops(Shops value) {
        this.shopId = value.shopId;
        this.name = value.name;
        this.latitude = value.latitude;
        this.longitude = value.longitude;
    }

    public Shops(
        ULong  shopId,
        String name,
        Double latitude,
        Double longitude
    ) {
        this.shopId = shopId;
        this.name = name;
        this.latitude = latitude;
        this.longitude = longitude;
    }

    /**
     * Getter for <code>shops.shop_id</code>.
     */
    public ULong getShopId() {
        return this.shopId;
    }

    /**
     * Getter for <code>shops.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>shops.latitude</code>.
     */
    public Double getLatitude() {
        return this.latitude;
    }

    /**
     * Getter for <code>shops.longitude</code>.
     */
    public Double getLongitude() {
        return this.longitude;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Shops (");

        sb.append(shopId);
        sb.append(", ").append(name);
        sb.append(", ").append(latitude);
        sb.append(", ").append(longitude);

        sb.append(")");
        return sb.toString();
    }
}
