/*
 * This file is generated by jOOQ.
 */
package store.pengu.server.db.pengustore.tables.pojos;


import java.io.Serializable;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SmartSorting implements Serializable {

    private static final long serialVersionUID = 1L;

    private final ULong   shoppingListId;
    private final String  rnumber;
    private final String  cnumber;
    private final Integer cval;

    public SmartSorting(SmartSorting value) {
        this.shoppingListId = value.shoppingListId;
        this.rnumber = value.rnumber;
        this.cnumber = value.cnumber;
        this.cval = value.cval;
    }

    public SmartSorting(
        ULong   shoppingListId,
        String  rnumber,
        String  cnumber,
        Integer cval
    ) {
        this.shoppingListId = shoppingListId;
        this.rnumber = rnumber;
        this.cnumber = cnumber;
        this.cval = cval;
    }

    /**
     * Getter for <code>smart_sorting.shopping_list_id</code>.
     */
    public ULong getShoppingListId() {
        return this.shoppingListId;
    }

    /**
     * Getter for <code>smart_sorting.rnumber</code>.
     */
    public String getRnumber() {
        return this.rnumber;
    }

    /**
     * Getter for <code>smart_sorting.cnumber</code>.
     */
    public String getCnumber() {
        return this.cnumber;
    }

    /**
     * Getter for <code>smart_sorting.cval</code>.
     */
    public Integer getCval() {
        return this.cval;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SmartSorting (");

        sb.append(shoppingListId);
        sb.append(", ").append(rnumber);
        sb.append(", ").append(cnumber);
        sb.append(", ").append(cval);

        sb.append(")");
        return sb.toString();
    }
}
