/*
 * This file is generated by jOOQ.
 */
package store.pengu.server.db.pengustore.tables.pojos;


import java.io.Serializable;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SmartSorting implements Serializable {

    private static final long serialVersionUID = 1L;

    private final ULong   rowNumber;
    private final ULong   colNumber;
    private final Integer cellVal;

    public SmartSorting(SmartSorting value) {
        this.rowNumber = value.rowNumber;
        this.colNumber = value.colNumber;
        this.cellVal = value.cellVal;
    }

    public SmartSorting(
        ULong   rowNumber,
        ULong   colNumber,
        Integer cellVal
    ) {
        this.rowNumber = rowNumber;
        this.colNumber = colNumber;
        this.cellVal = cellVal;
    }

    /**
     * Getter for <code>smart_sorting.row_number</code>.
     */
    public ULong getRowNumber() {
        return this.rowNumber;
    }

    /**
     * Getter for <code>smart_sorting.col_number</code>.
     */
    public ULong getColNumber() {
        return this.colNumber;
    }

    /**
     * Getter for <code>smart_sorting.cell_val</code>.
     */
    public Integer getCellVal() {
        return this.cellVal;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SmartSorting (");

        sb.append(rowNumber);
        sb.append(", ").append(colNumber);
        sb.append(", ").append(cellVal);

        sb.append(")");
        return sb.toString();
    }
}
