/*
 * This file is generated by jOOQ.
 */
package store.pengu.server.db.pengustore.tables.pojos;


import java.io.Serializable;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Suggestions implements Serializable {

    private static final long serialVersionUID = 1L;

    private final ULong   userId;
    private final String  rnumber;
    private final String  cnumber;
    private final Integer cval;

    public Suggestions(Suggestions value) {
        this.userId = value.userId;
        this.rnumber = value.rnumber;
        this.cnumber = value.cnumber;
        this.cval = value.cval;
    }

    public Suggestions(
        ULong   userId,
        String  rnumber,
        String  cnumber,
        Integer cval
    ) {
        this.userId = userId;
        this.rnumber = rnumber;
        this.cnumber = cnumber;
        this.cval = cval;
    }

    /**
     * Getter for <code>suggestions.user_id</code>.
     */
    public ULong getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>suggestions.rnumber</code>.
     */
    public String getRnumber() {
        return this.rnumber;
    }

    /**
     * Getter for <code>suggestions.cnumber</code>.
     */
    public String getCnumber() {
        return this.cnumber;
    }

    /**
     * Getter for <code>suggestions.cval</code>.
     */
    public Integer getCval() {
        return this.cval;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Suggestions (");

        sb.append(userId);
        sb.append(", ").append(rnumber);
        sb.append(", ").append(cnumber);
        sb.append(", ").append(cval);

        sb.append(")");
        return sb.toString();
    }
}
