/*
 * This file is generated by jOOQ.
 */
package store.pengu.server.db.pengustore.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Translation implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String string;
    private final String translation;

    public Translation(Translation value) {
        this.string = value.string;
        this.translation = value.translation;
    }

    public Translation(
        String string,
        String translation
    ) {
        this.string = string;
        this.translation = translation;
    }

    /**
     * Getter for <code>translation.string</code>.
     */
    public String getString() {
        return this.string;
    }

    /**
     * Getter for <code>translation.translation</code>.
     */
    public String getTranslation() {
        return this.translation;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Translation (");

        sb.append(string);
        sb.append(", ").append(translation);

        sb.append(")");
        return sb.toString();
    }
}
