/*
 * This file is generated by jOOQ.
 */
package store.pengu.server.db.pengustore.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Integer userid;
    private final String  name;

    public Users(Users value) {
        this.userid = value.userid;
        this.name = value.name;
    }

    public Users(
        Integer userid,
        String  name
    ) {
        this.userid = userid;
        this.name = name;
    }

    /**
     * Getter for <code>users.userid</code>.
     */
    public Integer getUserid() {
        return this.userid;
    }

    /**
     * Getter for <code>users.name</code>.
     */
    public String getName() {
        return this.name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(userid);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
