/*
 * This file is generated by jOOQ.
 */
package store.pengu.server.db.pengustore.tables.pojos;


import java.io.Serializable;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = 1L;

    private final ULong  userId;
    private final String username;
    private final String email;
    private final String password;

    public Users(Users value) {
        this.userId = value.userId;
        this.username = value.username;
        this.email = value.email;
        this.password = value.password;
    }

    public Users(
        ULong  userId,
        String username,
        String email,
        String password
    ) {
        this.userId = userId;
        this.username = username;
        this.email = email;
        this.password = password;
    }

    /**
     * Getter for <code>users.user_id</code>.
     */
    public ULong getUserId() {
        return this.userId;
    }

    /**
     * Getter for <code>users.username</code>.
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Getter for <code>users.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Getter for <code>users.password</code>.
     */
    public String getPassword() {
        return this.password;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(userId);
        sb.append(", ").append(username);
        sb.append(", ").append(email);
        sb.append(", ").append(password);

        sb.append(")");
        return sb.toString();
    }
}
