/*
 * This file is generated by jOOQ.
 */
package store.pengu.server.db.pengustore;


import store.pengu.server.db.pengustore.tables.Beacons;
import store.pengu.server.db.pengustore.tables.CrowdProductImages;
import store.pengu.server.db.pengustore.tables.CrowdProductPrices;
import store.pengu.server.db.pengustore.tables.LocalProductImages;
import store.pengu.server.db.pengustore.tables.LocalProductPrices;
import store.pengu.server.db.pengustore.tables.Pantries;
import store.pengu.server.db.pengustore.tables.PantriesUsers;
import store.pengu.server.db.pengustore.tables.PantryProducts;
import store.pengu.server.db.pengustore.tables.Products;
import store.pengu.server.db.pengustore.tables.ProductsUsers;
import store.pengu.server.db.pengustore.tables.Ratings;
import store.pengu.server.db.pengustore.tables.ShoppingList;
import store.pengu.server.db.pengustore.tables.ShoppingListUsers;
import store.pengu.server.db.pengustore.tables.Stats;
import store.pengu.server.db.pengustore.tables.Suggestions;
import store.pengu.server.db.pengustore.tables.Translation;
import store.pengu.server.db.pengustore.tables.Users;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>beacons</code>.
     */
    public static final Beacons BEACONS = Beacons.BEACONS;

    /**
     * The table <code>crowd_product_images</code>.
     */
    public static final CrowdProductImages CROWD_PRODUCT_IMAGES = CrowdProductImages.CROWD_PRODUCT_IMAGES;

    /**
     * The table <code>crowd_product_prices</code>.
     */
    public static final CrowdProductPrices CROWD_PRODUCT_PRICES = CrowdProductPrices.CROWD_PRODUCT_PRICES;

    /**
     * The table <code>local_product_images</code>.
     */
    public static final LocalProductImages LOCAL_PRODUCT_IMAGES = LocalProductImages.LOCAL_PRODUCT_IMAGES;

    /**
     * The table <code>local_product_prices</code>.
     */
    public static final LocalProductPrices LOCAL_PRODUCT_PRICES = LocalProductPrices.LOCAL_PRODUCT_PRICES;

    /**
     * The table <code>pantries</code>.
     */
    public static final Pantries PANTRIES = Pantries.PANTRIES;

    /**
     * The table <code>pantries_users</code>.
     */
    public static final PantriesUsers PANTRIES_USERS = PantriesUsers.PANTRIES_USERS;

    /**
     * The table <code>pantry_products</code>.
     */
    public static final PantryProducts PANTRY_PRODUCTS = PantryProducts.PANTRY_PRODUCTS;

    /**
     * The table <code>products</code>.
     */
    public static final Products PRODUCTS = Products.PRODUCTS;

    /**
     * The table <code>products_users</code>.
     */
    public static final ProductsUsers PRODUCTS_USERS = ProductsUsers.PRODUCTS_USERS;

    /**
     * The table <code>ratings</code>.
     */
    public static final Ratings RATINGS = Ratings.RATINGS;

    /**
     * The table <code>shopping_list</code>.
     */
    public static final ShoppingList SHOPPING_LIST = ShoppingList.SHOPPING_LIST;

    /**
     * The table <code>shopping_list_users</code>.
     */
    public static final ShoppingListUsers SHOPPING_LIST_USERS = ShoppingListUsers.SHOPPING_LIST_USERS;

    /**
     * The table <code>stats</code>.
     */
    public static final Stats STATS = Stats.STATS;

    /**
     * The table <code>suggestions</code>.
     */
    public static final Suggestions SUGGESTIONS = Suggestions.SUGGESTIONS;

    /**
     * The table <code>translation</code>.
     */
    public static final Translation TRANSLATION = Translation.TRANSLATION;

    /**
     * The table <code>users</code>.
     */
    public static final Users USERS = Users.USERS;
}
