/*
 * This file is generated by jOOQ.
 */
package store.pengu.server.db.pengustore;


import store.pengu.server.db.pengustore.tables.Pantries;
import store.pengu.server.db.pengustore.tables.PantryXUser;
import store.pengu.server.db.pengustore.tables.ProductXImage;
import store.pengu.server.db.pengustore.tables.ProductXPantry;
import store.pengu.server.db.pengustore.tables.Products;
import store.pengu.server.db.pengustore.tables.ShopXProduct;
import store.pengu.server.db.pengustore.tables.ShoppingList;
import store.pengu.server.db.pengustore.tables.Shops;
import store.pengu.server.db.pengustore.tables.Users;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>pantries</code>.
     */
    public static final Pantries PANTRIES = Pantries.PANTRIES;

    /**
     * The table <code>pantry_x_user</code>.
     */
    public static final PantryXUser PANTRY_X_USER = PantryXUser.PANTRY_X_USER;

    /**
     * The table <code>product_x_image</code>.
     */
    public static final ProductXImage PRODUCT_X_IMAGE = ProductXImage.PRODUCT_X_IMAGE;

    /**
     * The table <code>product_x_pantry</code>.
     */
    public static final ProductXPantry PRODUCT_X_PANTRY = ProductXPantry.PRODUCT_X_PANTRY;

    /**
     * The table <code>products</code>.
     */
    public static final Products PRODUCTS = Products.PRODUCTS;

    /**
     * The table <code>shop_x_product</code>.
     */
    public static final ShopXProduct SHOP_X_PRODUCT = ShopXProduct.SHOP_X_PRODUCT;

    /**
     * The table <code>shopping_list</code>.
     */
    public static final ShoppingList SHOPPING_LIST = ShoppingList.SHOPPING_LIST;

    /**
     * The table <code>shops</code>.
     */
    public static final Shops SHOPS = Shops.SHOPS;

    /**
     * The table <code>users</code>.
     */
    public static final Users USERS = Users.USERS;
}
