/*
 * This file is generated by jOOQ.
 */
package store.pengu.server.db.pengustore.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import store.pengu.server.db.pengustore.DefaultSchema;
import store.pengu.server.db.pengustore.Keys;
import store.pengu.server.db.pengustore.tables.records.CrowdProductPricesRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CrowdProductPrices extends TableImpl<CrowdProductPricesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>crowd_product_prices</code>
     */
    public static final CrowdProductPrices CROWD_PRODUCT_PRICES = new CrowdProductPrices();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CrowdProductPricesRecord> getRecordType() {
        return CrowdProductPricesRecord.class;
    }

    /**
     * The column <code>crowd_product_prices.barcode</code>.
     */
    public final TableField<CrowdProductPricesRecord, String> BARCODE = createField(DSL.name("barcode"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>crowd_product_prices.price</code>.
     */
    public final TableField<CrowdProductPricesRecord, Double> PRICE = createField(DSL.name("price"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>crowd_product_prices.latitude</code>.
     */
    public final TableField<CrowdProductPricesRecord, Double> LATITUDE = createField(DSL.name("latitude"), SQLDataType.FLOAT.nullable(false), this, "");

    /**
     * The column <code>crowd_product_prices.longitude</code>.
     */
    public final TableField<CrowdProductPricesRecord, Double> LONGITUDE = createField(DSL.name("longitude"), SQLDataType.FLOAT.nullable(false), this, "");

    private CrowdProductPrices(Name alias, Table<CrowdProductPricesRecord> aliased) {
        this(alias, aliased, null);
    }

    private CrowdProductPrices(Name alias, Table<CrowdProductPricesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>crowd_product_prices</code> table reference
     */
    public CrowdProductPrices(String alias) {
        this(DSL.name(alias), CROWD_PRODUCT_PRICES);
    }

    /**
     * Create an aliased <code>crowd_product_prices</code> table reference
     */
    public CrowdProductPrices(Name alias) {
        this(alias, CROWD_PRODUCT_PRICES);
    }

    /**
     * Create a <code>crowd_product_prices</code> table reference
     */
    public CrowdProductPrices() {
        this(DSL.name("crowd_product_prices"), null);
    }

    public <O extends Record> CrowdProductPrices(Table<O> child, ForeignKey<O, CrowdProductPricesRecord> key) {
        super(child, key, CROWD_PRODUCT_PRICES);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<CrowdProductPricesRecord> getPrimaryKey() {
        return Keys.KEY_CROWD_PRODUCT_PRICES_PRIMARY;
    }

    @Override
    public List<UniqueKey<CrowdProductPricesRecord>> getKeys() {
        return Arrays.<UniqueKey<CrowdProductPricesRecord>>asList(Keys.KEY_CROWD_PRODUCT_PRICES_PRIMARY);
    }

    @Override
    public CrowdProductPrices as(String alias) {
        return new CrowdProductPrices(DSL.name(alias), this);
    }

    @Override
    public CrowdProductPrices as(Name alias) {
        return new CrowdProductPrices(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CrowdProductPrices rename(String name) {
        return new CrowdProductPrices(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CrowdProductPrices rename(Name name) {
        return new CrowdProductPrices(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, Double, Double, Double> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
