/*
 * This file is generated by jOOQ.
 */
package store.pengu.server.db.pengustore.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;

import store.pengu.server.db.pengustore.DefaultSchema;
import store.pengu.server.db.pengustore.Keys;
import store.pengu.server.db.pengustore.tables.records.CrowdProductImagesRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CrowdProductImages extends TableImpl<CrowdProductImagesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>crowd_product_images</code>
     */
    public static final CrowdProductImages CROWD_PRODUCT_IMAGES = new CrowdProductImages();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CrowdProductImagesRecord> getRecordType() {
        return CrowdProductImagesRecord.class;
    }

    /**
     * The column <code>crowd_product_images.id</code>.
     */
    public final TableField<CrowdProductImagesRecord, ULong> ID = createField(DSL.name("id"), SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>crowd_product_images.barcode</code>.
     */
    public final TableField<CrowdProductImagesRecord, String> BARCODE = createField(DSL.name("barcode"), SQLDataType.VARCHAR(255).defaultValue(DSL.inline("NULL", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>crowd_product_images.image_url</code>.
     */
    public final TableField<CrowdProductImagesRecord, String> IMAGE_URL = createField(DSL.name("image_url"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private CrowdProductImages(Name alias, Table<CrowdProductImagesRecord> aliased) {
        this(alias, aliased, null);
    }

    private CrowdProductImages(Name alias, Table<CrowdProductImagesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>crowd_product_images</code> table reference
     */
    public CrowdProductImages(String alias) {
        this(DSL.name(alias), CROWD_PRODUCT_IMAGES);
    }

    /**
     * Create an aliased <code>crowd_product_images</code> table reference
     */
    public CrowdProductImages(Name alias) {
        this(alias, CROWD_PRODUCT_IMAGES);
    }

    /**
     * Create a <code>crowd_product_images</code> table reference
     */
    public CrowdProductImages() {
        this(DSL.name("crowd_product_images"), null);
    }

    public <O extends Record> CrowdProductImages(Table<O> child, ForeignKey<O, CrowdProductImagesRecord> key) {
        super(child, key, CROWD_PRODUCT_IMAGES);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<CrowdProductImagesRecord, ULong> getIdentity() {
        return (Identity<CrowdProductImagesRecord, ULong>) super.getIdentity();
    }

    @Override
    public UniqueKey<CrowdProductImagesRecord> getPrimaryKey() {
        return Keys.KEY_CROWD_PRODUCT_IMAGES_PRIMARY;
    }

    @Override
    public List<UniqueKey<CrowdProductImagesRecord>> getKeys() {
        return Arrays.<UniqueKey<CrowdProductImagesRecord>>asList(Keys.KEY_CROWD_PRODUCT_IMAGES_PRIMARY);
    }

    @Override
    public CrowdProductImages as(String alias) {
        return new CrowdProductImages(DSL.name(alias), this);
    }

    @Override
    public CrowdProductImages as(Name alias) {
        return new CrowdProductImages(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CrowdProductImages rename(String name) {
        return new CrowdProductImages(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CrowdProductImages rename(Name name) {
        return new CrowdProductImages(name, null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<ULong, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }
}
