/*
 * This file is generated by jOOQ.
 */
package store.pengu.server.db.pengustore.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;

import store.pengu.server.db.pengustore.DefaultSchema;
import store.pengu.server.db.pengustore.Keys;
import store.pengu.server.db.pengustore.tables.records.PantriesRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Pantries extends TableImpl<PantriesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>pantries</code>
     */
    public static final Pantries PANTRIES = new Pantries();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PantriesRecord> getRecordType() {
        return PantriesRecord.class;
    }

    /**
     * The column <code>pantries.id</code>.
     */
    public final TableField<PantriesRecord, ULong> ID = createField(DSL.name("id"), SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>pantries.code</code>.
     */
    public final TableField<PantriesRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>pantries.name</code>.
     */
    public final TableField<PantriesRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>pantries.latitude</code>.
     */
    public final TableField<PantriesRecord, Double> LATITUDE = createField(DSL.name("latitude"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>pantries.longitude</code>.
     */
    public final TableField<PantriesRecord, Double> LONGITUDE = createField(DSL.name("longitude"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>pantries.color</code>.
     */
    public final TableField<PantriesRecord, String> COLOR = createField(DSL.name("color"), SQLDataType.VARCHAR(12).nullable(false), this, "");

    private Pantries(Name alias, Table<PantriesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Pantries(Name alias, Table<PantriesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>pantries</code> table reference
     */
    public Pantries(String alias) {
        this(DSL.name(alias), PANTRIES);
    }

    /**
     * Create an aliased <code>pantries</code> table reference
     */
    public Pantries(Name alias) {
        this(alias, PANTRIES);
    }

    /**
     * Create a <code>pantries</code> table reference
     */
    public Pantries() {
        this(DSL.name("pantries"), null);
    }

    public <O extends Record> Pantries(Table<O> child, ForeignKey<O, PantriesRecord> key) {
        super(child, key, PANTRIES);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<PantriesRecord, ULong> getIdentity() {
        return (Identity<PantriesRecord, ULong>) super.getIdentity();
    }

    @Override
    public UniqueKey<PantriesRecord> getPrimaryKey() {
        return Keys.KEY_PANTRIES_PRIMARY;
    }

    @Override
    public List<UniqueKey<PantriesRecord>> getKeys() {
        return Arrays.<UniqueKey<PantriesRecord>>asList(Keys.KEY_PANTRIES_PRIMARY, Keys.KEY_PANTRIES_CODE);
    }

    @Override
    public Pantries as(String alias) {
        return new Pantries(DSL.name(alias), this);
    }

    @Override
    public Pantries as(Name alias) {
        return new Pantries(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Pantries rename(String name) {
        return new Pantries(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Pantries rename(Name name) {
        return new Pantries(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<ULong, String, String, Double, Double, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
