/*
 * This file is generated by jOOQ.
 */
package store.pengu.server.db.pengustore.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import store.pengu.server.db.pengustore.DefaultSchema;
import store.pengu.server.db.pengustore.Keys;
import store.pengu.server.db.pengustore.tables.records.PantryXUserRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PantryXUser extends TableImpl<PantryXUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>pantry_x_user</code>
     */
    public static final PantryXUser PANTRY_X_USER = new PantryXUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PantryXUserRecord> getRecordType() {
        return PantryXUserRecord.class;
    }

    /**
     * The column <code>pantry_x_user.pantry_id</code>.
     */
    public final TableField<PantryXUserRecord, Long> PANTRY_ID = createField(DSL.name("pantry_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>pantry_x_user.user_id</code>.
     */
    public final TableField<PantryXUserRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private PantryXUser(Name alias, Table<PantryXUserRecord> aliased) {
        this(alias, aliased, null);
    }

    private PantryXUser(Name alias, Table<PantryXUserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>pantry_x_user</code> table reference
     */
    public PantryXUser(String alias) {
        this(DSL.name(alias), PANTRY_X_USER);
    }

    /**
     * Create an aliased <code>pantry_x_user</code> table reference
     */
    public PantryXUser(Name alias) {
        this(alias, PANTRY_X_USER);
    }

    /**
     * Create a <code>pantry_x_user</code> table reference
     */
    public PantryXUser() {
        this(DSL.name("pantry_x_user"), null);
    }

    public <O extends Record> PantryXUser(Table<O> child, ForeignKey<O, PantryXUserRecord> key) {
        super(child, key, PANTRY_X_USER);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<PantryXUserRecord> getPrimaryKey() {
        return Keys.KEY_PANTRY_X_USER_PRIMARY;
    }

    @Override
    public List<UniqueKey<PantryXUserRecord>> getKeys() {
        return Arrays.<UniqueKey<PantryXUserRecord>>asList(Keys.KEY_PANTRY_X_USER_PRIMARY);
    }

    @Override
    public PantryXUser as(String alias) {
        return new PantryXUser(DSL.name(alias), this);
    }

    @Override
    public PantryXUser as(Name alias) {
        return new PantryXUser(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PantryXUser rename(String name) {
        return new PantryXUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PantryXUser rename(Name name) {
        return new PantryXUser(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
