/*
 * This file is generated by jOOQ.
 */
package store.pengu.server.db.pengustore.tables;


import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;

import store.pengu.server.db.pengustore.DefaultSchema;
import store.pengu.server.db.pengustore.Indexes;
import store.pengu.server.db.pengustore.Keys;
import store.pengu.server.db.pengustore.tables.records.ProductsUsersRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductsUsers extends TableImpl<ProductsUsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>products_users</code>
     */
    public static final ProductsUsers PRODUCTS_USERS = new ProductsUsers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProductsUsersRecord> getRecordType() {
        return ProductsUsersRecord.class;
    }

    /**
     * The column <code>products_users.product_id</code>.
     */
    public final TableField<ProductsUsersRecord, ULong> PRODUCT_ID = createField(DSL.name("product_id"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>products_users.user_id</code>.
     */
    public final TableField<ProductsUsersRecord, ULong> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    private ProductsUsers(Name alias, Table<ProductsUsersRecord> aliased) {
        this(alias, aliased, null);
    }

    private ProductsUsers(Name alias, Table<ProductsUsersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>products_users</code> table reference
     */
    public ProductsUsers(String alias) {
        this(DSL.name(alias), PRODUCTS_USERS);
    }

    /**
     * Create an aliased <code>products_users</code> table reference
     */
    public ProductsUsers(Name alias) {
        this(alias, PRODUCTS_USERS);
    }

    /**
     * Create a <code>products_users</code> table reference
     */
    public ProductsUsers() {
        this(DSL.name("products_users"), null);
    }

    public <O extends Record> ProductsUsers(Table<O> child, ForeignKey<O, ProductsUsersRecord> key) {
        super(child, key, PRODUCTS_USERS);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRODUCTS_USERS_USER_ID);
    }

    @Override
    public UniqueKey<ProductsUsersRecord> getPrimaryKey() {
        return Keys.KEY_PRODUCTS_USERS_PRIMARY;
    }

    @Override
    public List<UniqueKey<ProductsUsersRecord>> getKeys() {
        return Arrays.<UniqueKey<ProductsUsersRecord>>asList(Keys.KEY_PRODUCTS_USERS_PRIMARY);
    }

    @Override
    public List<ForeignKey<ProductsUsersRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ProductsUsersRecord, ?>>asList(Keys.PRODUCTS_USERS_IBFK_1, Keys.PRODUCTS_USERS_IBFK_2);
    }

    private transient Products _products;
    private transient Users _users;

    public Products products() {
        if (_products == null)
            _products = new Products(this, Keys.PRODUCTS_USERS_IBFK_1);

        return _products;
    }

    public Users users() {
        if (_users == null)
            _users = new Users(this, Keys.PRODUCTS_USERS_IBFK_2);

        return _users;
    }

    @Override
    public ProductsUsers as(String alias) {
        return new ProductsUsers(DSL.name(alias), this);
    }

    @Override
    public ProductsUsers as(Name alias) {
        return new ProductsUsers(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductsUsers rename(String name) {
        return new ProductsUsers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductsUsers rename(Name name) {
        return new ProductsUsers(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<ULong, ULong> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
