/*
 * This file is generated by jOOQ.
 */
package store.pengu.server.db.pengustore.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;

import store.pengu.server.db.pengustore.tables.CrowdProductImages;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CrowdProductImagesRecord extends UpdatableRecordImpl<CrowdProductImagesRecord> implements Record3<ULong, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>crowd_product_images.id</code>.
     */
    public CrowdProductImagesRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>crowd_product_images.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>crowd_product_images.barcode</code>.
     */
    public CrowdProductImagesRecord setBarcode(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>crowd_product_images.barcode</code>.
     */
    public String getBarcode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>crowd_product_images.image_url</code>.
     */
    public CrowdProductImagesRecord setImageUrl(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>crowd_product_images.image_url</code>.
     */
    public String getImageUrl() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<ULong, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<ULong, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<ULong> field1() {
        return CrowdProductImages.CROWD_PRODUCT_IMAGES.ID;
    }

    @Override
    public Field<String> field2() {
        return CrowdProductImages.CROWD_PRODUCT_IMAGES.BARCODE;
    }

    @Override
    public Field<String> field3() {
        return CrowdProductImages.CROWD_PRODUCT_IMAGES.IMAGE_URL;
    }

    @Override
    public ULong component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getBarcode();
    }

    @Override
    public String component3() {
        return getImageUrl();
    }

    @Override
    public ULong value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getBarcode();
    }

    @Override
    public String value3() {
        return getImageUrl();
    }

    @Override
    public CrowdProductImagesRecord value1(ULong value) {
        setId(value);
        return this;
    }

    @Override
    public CrowdProductImagesRecord value2(String value) {
        setBarcode(value);
        return this;
    }

    @Override
    public CrowdProductImagesRecord value3(String value) {
        setImageUrl(value);
        return this;
    }

    @Override
    public CrowdProductImagesRecord values(ULong value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CrowdProductImagesRecord
     */
    public CrowdProductImagesRecord() {
        super(CrowdProductImages.CROWD_PRODUCT_IMAGES);
    }

    /**
     * Create a detached, initialised CrowdProductImagesRecord
     */
    public CrowdProductImagesRecord(ULong id, String barcode, String imageUrl) {
        super(CrowdProductImages.CROWD_PRODUCT_IMAGES);

        setId(id);
        setBarcode(barcode);
        setImageUrl(imageUrl);
    }
}
