/*
 * This file is generated by jOOQ.
 */
package store.pengu.server.db.pengustore.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;

import store.pengu.server.db.pengustore.tables.LocalProductPrices;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LocalProductPricesRecord extends UpdatableRecordImpl<LocalProductPricesRecord> implements Record4<ULong, Double, Double, Double> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>local_product_prices.product_id</code>.
     */
    public LocalProductPricesRecord setProductId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>local_product_prices.product_id</code>.
     */
    public ULong getProductId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>local_product_prices.price</code>.
     */
    public LocalProductPricesRecord setPrice(Double value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>local_product_prices.price</code>.
     */
    public Double getPrice() {
        return (Double) get(1);
    }

    /**
     * Setter for <code>local_product_prices.latitude</code>.
     */
    public LocalProductPricesRecord setLatitude(Double value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>local_product_prices.latitude</code>.
     */
    public Double getLatitude() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>local_product_prices.longitude</code>.
     */
    public LocalProductPricesRecord setLongitude(Double value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>local_product_prices.longitude</code>.
     */
    public Double getLongitude() {
        return (Double) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<ULong, Double, Double, Double> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<ULong, Double, Double, Double> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<ULong> field1() {
        return LocalProductPrices.LOCAL_PRODUCT_PRICES.PRODUCT_ID;
    }

    @Override
    public Field<Double> field2() {
        return LocalProductPrices.LOCAL_PRODUCT_PRICES.PRICE;
    }

    @Override
    public Field<Double> field3() {
        return LocalProductPrices.LOCAL_PRODUCT_PRICES.LATITUDE;
    }

    @Override
    public Field<Double> field4() {
        return LocalProductPrices.LOCAL_PRODUCT_PRICES.LONGITUDE;
    }

    @Override
    public ULong component1() {
        return getProductId();
    }

    @Override
    public Double component2() {
        return getPrice();
    }

    @Override
    public Double component3() {
        return getLatitude();
    }

    @Override
    public Double component4() {
        return getLongitude();
    }

    @Override
    public ULong value1() {
        return getProductId();
    }

    @Override
    public Double value2() {
        return getPrice();
    }

    @Override
    public Double value3() {
        return getLatitude();
    }

    @Override
    public Double value4() {
        return getLongitude();
    }

    @Override
    public LocalProductPricesRecord value1(ULong value) {
        setProductId(value);
        return this;
    }

    @Override
    public LocalProductPricesRecord value2(Double value) {
        setPrice(value);
        return this;
    }

    @Override
    public LocalProductPricesRecord value3(Double value) {
        setLatitude(value);
        return this;
    }

    @Override
    public LocalProductPricesRecord value4(Double value) {
        setLongitude(value);
        return this;
    }

    @Override
    public LocalProductPricesRecord values(ULong value1, Double value2, Double value3, Double value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LocalProductPricesRecord
     */
    public LocalProductPricesRecord() {
        super(LocalProductPrices.LOCAL_PRODUCT_PRICES);
    }

    /**
     * Create a detached, initialised LocalProductPricesRecord
     */
    public LocalProductPricesRecord(ULong productId, Double price, Double latitude, Double longitude) {
        super(LocalProductPrices.LOCAL_PRODUCT_PRICES);

        setProductId(productId);
        setPrice(price);
        setLatitude(latitude);
        setLongitude(longitude);
    }
}
