/*
 * This file is generated by jOOQ.
 */
package store.pengu.server.db.pengustore.tables.records;


import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;

import store.pengu.server.db.pengustore.tables.PantriesUsers;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PantriesUsersRecord extends UpdatableRecordImpl<PantriesUsersRecord> implements Record2<ULong, ULong> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>pantries_users.pantry_id</code>.
     */
    public PantriesUsersRecord setPantryId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>pantries_users.pantry_id</code>.
     */
    public ULong getPantryId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>pantries_users.user_id</code>.
     */
    public PantriesUsersRecord setUserId(ULong value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>pantries_users.user_id</code>.
     */
    public ULong getUserId() {
        return (ULong) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<ULong, ULong> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<ULong, ULong> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<ULong, ULong> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<ULong> field1() {
        return PantriesUsers.PANTRIES_USERS.PANTRY_ID;
    }

    @Override
    public Field<ULong> field2() {
        return PantriesUsers.PANTRIES_USERS.USER_ID;
    }

    @Override
    public ULong component1() {
        return getPantryId();
    }

    @Override
    public ULong component2() {
        return getUserId();
    }

    @Override
    public ULong value1() {
        return getPantryId();
    }

    @Override
    public ULong value2() {
        return getUserId();
    }

    @Override
    public PantriesUsersRecord value1(ULong value) {
        setPantryId(value);
        return this;
    }

    @Override
    public PantriesUsersRecord value2(ULong value) {
        setUserId(value);
        return this;
    }

    @Override
    public PantriesUsersRecord values(ULong value1, ULong value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PantriesUsersRecord
     */
    public PantriesUsersRecord() {
        super(PantriesUsers.PANTRIES_USERS);
    }

    /**
     * Create a detached, initialised PantriesUsersRecord
     */
    public PantriesUsersRecord(ULong pantryId, ULong userId) {
        super(PantriesUsers.PANTRIES_USERS);

        setPantryId(pantryId);
        setUserId(userId);
    }
}
