/*
 * This file is generated by jOOQ.
 */
package store.pengu.server.db.pengustore.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;

import store.pengu.server.db.pengustore.tables.Products;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductsRecord extends UpdatableRecordImpl<ProductsRecord> implements Record5<ULong, String, Double, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>products.product_id</code>.
     */
    public ProductsRecord setProductId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>products.product_id</code>.
     */
    public ULong getProductId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>products.barcode</code>.
     */
    public ProductsRecord setBarcode(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>products.barcode</code>.
     */
    public String getBarcode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>products.review_score</code>.
     */
    public ProductsRecord setReviewScore(Double value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>products.review_score</code>.
     */
    public Double getReviewScore() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>products.review_number</code>.
     */
    public ProductsRecord setReviewNumber(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>products.review_number</code>.
     */
    public Integer getReviewNumber() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>products.name</code>.
     */
    public ProductsRecord setName(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>products.name</code>.
     */
    public String getName() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<ULong, String, Double, Integer, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<ULong, String, Double, Integer, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<ULong> field1() {
        return Products.PRODUCTS.PRODUCT_ID;
    }

    @Override
    public Field<String> field2() {
        return Products.PRODUCTS.BARCODE;
    }

    @Override
    public Field<Double> field3() {
        return Products.PRODUCTS.REVIEW_SCORE;
    }

    @Override
    public Field<Integer> field4() {
        return Products.PRODUCTS.REVIEW_NUMBER;
    }

    @Override
    public Field<String> field5() {
        return Products.PRODUCTS.NAME;
    }

    @Override
    public ULong component1() {
        return getProductId();
    }

    @Override
    public String component2() {
        return getBarcode();
    }

    @Override
    public Double component3() {
        return getReviewScore();
    }

    @Override
    public Integer component4() {
        return getReviewNumber();
    }

    @Override
    public String component5() {
        return getName();
    }

    @Override
    public ULong value1() {
        return getProductId();
    }

    @Override
    public String value2() {
        return getBarcode();
    }

    @Override
    public Double value3() {
        return getReviewScore();
    }

    @Override
    public Integer value4() {
        return getReviewNumber();
    }

    @Override
    public String value5() {
        return getName();
    }

    @Override
    public ProductsRecord value1(ULong value) {
        setProductId(value);
        return this;
    }

    @Override
    public ProductsRecord value2(String value) {
        setBarcode(value);
        return this;
    }

    @Override
    public ProductsRecord value3(Double value) {
        setReviewScore(value);
        return this;
    }

    @Override
    public ProductsRecord value4(Integer value) {
        setReviewNumber(value);
        return this;
    }

    @Override
    public ProductsRecord value5(String value) {
        setName(value);
        return this;
    }

    @Override
    public ProductsRecord values(ULong value1, String value2, Double value3, Integer value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductsRecord
     */
    public ProductsRecord() {
        super(Products.PRODUCTS);
    }

    /**
     * Create a detached, initialised ProductsRecord
     */
    public ProductsRecord(ULong productId, String barcode, Double reviewScore, Integer reviewNumber, String name) {
        super(Products.PRODUCTS);

        setProductId(productId);
        setBarcode(barcode);
        setReviewScore(reviewScore);
        setReviewNumber(reviewNumber);
        setName(name);
    }
}
