/*
 * This file is generated by jOOQ.
 */
package store.pengu.server.db.pengustore.tables.records;


import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import store.pengu.server.db.pengustore.tables.ProductXPantry;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductXPantryRecord extends UpdatableRecordImpl<ProductXPantryRecord> implements Record4<Long, Long, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>product_x_pantry.pantry_id</code>.
     */
    public ProductXPantryRecord setPantryId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>product_x_pantry.pantry_id</code>.
     */
    public Long getPantryId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>product_x_pantry.product_id</code>.
     */
    public ProductXPantryRecord setProductId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>product_x_pantry.product_id</code>.
     */
    public Long getProductId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>product_x_pantry.have_qty</code>.
     */
    public ProductXPantryRecord setHaveQty(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>product_x_pantry.have_qty</code>.
     */
    public Integer getHaveQty() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>product_x_pantry.want_qty</code>.
     */
    public ProductXPantryRecord setWantQty(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>product_x_pantry.want_qty</code>.
     */
    public Integer getWantQty() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Long, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, Long, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return ProductXPantry.PRODUCT_X_PANTRY.PANTRY_ID;
    }

    @Override
    public Field<Long> field2() {
        return ProductXPantry.PRODUCT_X_PANTRY.PRODUCT_ID;
    }

    @Override
    public Field<Integer> field3() {
        return ProductXPantry.PRODUCT_X_PANTRY.HAVE_QTY;
    }

    @Override
    public Field<Integer> field4() {
        return ProductXPantry.PRODUCT_X_PANTRY.WANT_QTY;
    }

    @Override
    public Long component1() {
        return getPantryId();
    }

    @Override
    public Long component2() {
        return getProductId();
    }

    @Override
    public Integer component3() {
        return getHaveQty();
    }

    @Override
    public Integer component4() {
        return getWantQty();
    }

    @Override
    public Long value1() {
        return getPantryId();
    }

    @Override
    public Long value2() {
        return getProductId();
    }

    @Override
    public Integer value3() {
        return getHaveQty();
    }

    @Override
    public Integer value4() {
        return getWantQty();
    }

    @Override
    public ProductXPantryRecord value1(Long value) {
        setPantryId(value);
        return this;
    }

    @Override
    public ProductXPantryRecord value2(Long value) {
        setProductId(value);
        return this;
    }

    @Override
    public ProductXPantryRecord value3(Integer value) {
        setHaveQty(value);
        return this;
    }

    @Override
    public ProductXPantryRecord value4(Integer value) {
        setWantQty(value);
        return this;
    }

    @Override
    public ProductXPantryRecord values(Long value1, Long value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductXPantryRecord
     */
    public ProductXPantryRecord() {
        super(ProductXPantry.PRODUCT_X_PANTRY);
    }

    /**
     * Create a detached, initialised ProductXPantryRecord
     */
    public ProductXPantryRecord(Long pantryId, Long productId, Integer haveQty, Integer wantQty) {
        super(ProductXPantry.PRODUCT_X_PANTRY);

        setPantryId(pantryId);
        setProductId(productId);
        setHaveQty(haveQty);
        setWantQty(wantQty);
    }
}
