/*
 * This file is generated by jOOQ.
 */
package store.pengu.server.db.pengustore.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;

import store.pengu.server.db.pengustore.tables.Ratings;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RatingsRecord extends UpdatableRecordImpl<RatingsRecord> implements Record3<ULong, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ratings.id</code>.
     */
    public RatingsRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>ratings.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>ratings.barcode</code>.
     */
    public RatingsRecord setBarcode(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>ratings.barcode</code>.
     */
    public String getBarcode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ratings.rating</code>.
     */
    public RatingsRecord setRating(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>ratings.rating</code>.
     */
    public Integer getRating() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<ULong, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<ULong, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<ULong> field1() {
        return Ratings.RATINGS.ID;
    }

    @Override
    public Field<String> field2() {
        return Ratings.RATINGS.BARCODE;
    }

    @Override
    public Field<Integer> field3() {
        return Ratings.RATINGS.RATING;
    }

    @Override
    public ULong component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getBarcode();
    }

    @Override
    public Integer component3() {
        return getRating();
    }

    @Override
    public ULong value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getBarcode();
    }

    @Override
    public Integer value3() {
        return getRating();
    }

    @Override
    public RatingsRecord value1(ULong value) {
        setId(value);
        return this;
    }

    @Override
    public RatingsRecord value2(String value) {
        setBarcode(value);
        return this;
    }

    @Override
    public RatingsRecord value3(Integer value) {
        setRating(value);
        return this;
    }

    @Override
    public RatingsRecord values(ULong value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RatingsRecord
     */
    public RatingsRecord() {
        super(Ratings.RATINGS);
    }

    /**
     * Create a detached, initialised RatingsRecord
     */
    public RatingsRecord(ULong id, String barcode, Integer rating) {
        super(Ratings.RATINGS);

        setId(id);
        setBarcode(barcode);
        setRating(rating);
    }
}
