/*
 * This file is generated by jOOQ.
 */
package store.pengu.server.db.pengustore.tables.records;


import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;

import store.pengu.server.db.pengustore.tables.ShoppingListUsers;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShoppingListUsersRecord extends UpdatableRecordImpl<ShoppingListUsersRecord> implements Record2<ULong, ULong> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>shopping_list_users.shopping_list_id</code>.
     */
    public ShoppingListUsersRecord setShoppingListId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>shopping_list_users.shopping_list_id</code>.
     */
    public ULong getShoppingListId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>shopping_list_users.user_id</code>.
     */
    public ShoppingListUsersRecord setUserId(ULong value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>shopping_list_users.user_id</code>.
     */
    public ULong getUserId() {
        return (ULong) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<ULong, ULong> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<ULong, ULong> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<ULong, ULong> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<ULong> field1() {
        return ShoppingListUsers.SHOPPING_LIST_USERS.SHOPPING_LIST_ID;
    }

    @Override
    public Field<ULong> field2() {
        return ShoppingListUsers.SHOPPING_LIST_USERS.USER_ID;
    }

    @Override
    public ULong component1() {
        return getShoppingListId();
    }

    @Override
    public ULong component2() {
        return getUserId();
    }

    @Override
    public ULong value1() {
        return getShoppingListId();
    }

    @Override
    public ULong value2() {
        return getUserId();
    }

    @Override
    public ShoppingListUsersRecord value1(ULong value) {
        setShoppingListId(value);
        return this;
    }

    @Override
    public ShoppingListUsersRecord value2(ULong value) {
        setUserId(value);
        return this;
    }

    @Override
    public ShoppingListUsersRecord values(ULong value1, ULong value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShoppingListUsersRecord
     */
    public ShoppingListUsersRecord() {
        super(ShoppingListUsers.SHOPPING_LIST_USERS);
    }

    /**
     * Create a detached, initialised ShoppingListUsersRecord
     */
    public ShoppingListUsersRecord(ULong shoppingListId, ULong userId) {
        super(ShoppingListUsers.SHOPPING_LIST_USERS);

        setShoppingListId(shoppingListId);
        setUserId(userId);
    }
}
