/*
 * This file is generated by jOOQ.
 */
package store.pengu.server.db.pengustore.tables.records;


import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;

import store.pengu.server.db.pengustore.tables.SmartSorting;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SmartSortingRecord extends UpdatableRecordImpl<SmartSortingRecord> implements Record4<ULong, String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>smart_sorting.shopping_list_id</code>.
     */
    public SmartSortingRecord setShoppingListId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>smart_sorting.shopping_list_id</code>.
     */
    public ULong getShoppingListId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>smart_sorting.row_number</code>.
     */
    public SmartSortingRecord setRowNumber(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>smart_sorting.row_number</code>.
     */
    public String getRowNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>smart_sorting.col_number</code>.
     */
    public SmartSortingRecord setColNumber(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>smart_sorting.col_number</code>.
     */
    public String getColNumber() {
        return (String) get(2);
    }

    /**
     * Setter for <code>smart_sorting.cell_val</code>.
     */
    public SmartSortingRecord setCellVal(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>smart_sorting.cell_val</code>.
     */
    public Integer getCellVal() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<ULong, String, String> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<ULong, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<ULong, String, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<ULong> field1() {
        return SmartSorting.SMART_SORTING.SHOPPING_LIST_ID;
    }

    @Override
    public Field<String> field2() {
        return SmartSorting.SMART_SORTING.ROW_NUMBER;
    }

    @Override
    public Field<String> field3() {
        return SmartSorting.SMART_SORTING.COL_NUMBER;
    }

    @Override
    public Field<Integer> field4() {
        return SmartSorting.SMART_SORTING.CELL_VAL;
    }

    @Override
    public ULong component1() {
        return getShoppingListId();
    }

    @Override
    public String component2() {
        return getRowNumber();
    }

    @Override
    public String component3() {
        return getColNumber();
    }

    @Override
    public Integer component4() {
        return getCellVal();
    }

    @Override
    public ULong value1() {
        return getShoppingListId();
    }

    @Override
    public String value2() {
        return getRowNumber();
    }

    @Override
    public String value3() {
        return getColNumber();
    }

    @Override
    public Integer value4() {
        return getCellVal();
    }

    @Override
    public SmartSortingRecord value1(ULong value) {
        setShoppingListId(value);
        return this;
    }

    @Override
    public SmartSortingRecord value2(String value) {
        setRowNumber(value);
        return this;
    }

    @Override
    public SmartSortingRecord value3(String value) {
        setColNumber(value);
        return this;
    }

    @Override
    public SmartSortingRecord value4(Integer value) {
        setCellVal(value);
        return this;
    }

    @Override
    public SmartSortingRecord values(ULong value1, String value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SmartSortingRecord
     */
    public SmartSortingRecord() {
        super(SmartSorting.SMART_SORTING);
    }

    /**
     * Create a detached, initialised SmartSortingRecord
     */
    public SmartSortingRecord(ULong shoppingListId, String rowNumber, String colNumber, Integer cellVal) {
        super(SmartSorting.SMART_SORTING);

        setShoppingListId(shoppingListId);
        setRowNumber(rowNumber);
        setColNumber(colNumber);
        setCellVal(cellVal);
    }
}
